# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9.4
# cache: cocoapods
# podfile: Example/Podfile

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --repo-update --project-directory=Example

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EthereumUnitSwift.xcworkspace -scheme EthereumUnitSwift-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty
  - pod lib lint

